### ISSUE TITLE
貌似android 8.0不行

### ISSUE THREAD

**Issue by JamesLiAndroid** [KB5201314/ZjDroid#2]
我用android 8.0的机器安装的，

按照博客中的步骤执行的时候，出现了一下日志信息：

06-27 05:58:56.355 15232 15232 E zjdroid-shell-com.imlk.BlackAndWhite: the cmd = baksmali
06-27 05:58:56.355 15232 15232 E zjdroid-shell-com.imlk.BlackAndWhite: baksmali cmd is invalid!
06-27 05:58:56.355 15232 15232 E zjdroid-shell-com.imlk.BlackAndWhite: the cmd is invalid
06-27 05:59:26.953 15232 15232 E zjdroid-shell-com.imlk.BlackAndWhite: the cmd = backsmali
06-27 05:59:26.961 15232 15232 E zjdroid-shell-com.imlk.BlackAndWhite: please set the mCookie value
06-27 05:59:26.961 15232 15232 E zjdroid-shell-com.imlk.BlackAndWhite: the cmd is invalid
06-27 06:01:56.215 15232 15232 E zjdroid-shell-com.imlk.BlackAndWhite: the cmd = dump_class
06-27 06:01:56.215 15232 15232 E zjdroid-shell-com.imlk.BlackAndWhite: please set the mCookie value
06-27 06:01:56.215 15232 15232 E zjdroid-shell-com.imlk.BlackAndWhite: the cmd is invalid

这个怎么破？

**Comment by JamesLiAndroid** [comment]
同时，在执行

am broadcast -a com.zjdroid.invoke --ei target 15232 --es cmd '{action:dump_dexinfo}'

的时候出现了如下日志：

06-27 05:56:40.649 15232 15232 E zjdroid-shell-com.imlk.BlackAndWhite: the cmd = dump_dexinfo
06-27 05:56:40.652 15232 18875 E zjdroid-shell-com.imlk.BlackAndWhite: The DexFile Infomation ->
06-27 05:56:40.652 15232 18875 E zjdroid-shell-com.imlk.BlackAndWhite: filepath:/data/app/com.imlk.BlackAndWhite-aGw9kjsTnAgf0XbbE7Kp9A==/base.apk dexElementToString:dex file "/data/app/com.imlk.BlackAndWhite-aGw9kjsTnAgf0XbbE7Kp9A==/base.apk" mCookie:3865175168
06-27 05:56:40.652 15232 18875 E zjdroid-shell-com.imlk.BlackAndWhite: filepath:/data/app/com.imlk.BlackAndWhite-aGw9kjsTnAgf0XbbE7Kp9A==/base.apk dexElementToString:null mCookie:3865175888
06-27 05:56:40.652 15232 18875 E zjdroid-shell-com.imlk.BlackAndWhite: filepath:/data/app/com.imlk.BlackAndWhite-aGw9kjsTnAgf0XbbE7Kp9A==/base.apk dexElementToString:dex file "/data/app/com.imlk.BlackAndWhite-aGw9kjsTnAgf0XbbE7Kp9A==/base.apk" mCookie:3865174928
06-27 05:56:40.652 15232 18875 E zjdroid-shell-com.imlk.BlackAndWhite: filepath:/data/app/com.imlk.BlackAndWhite-aGw9kjsTnAgf0XbbE7Kp9A==/base.apk dexElementToString:zip file "/data/app/com.imlk.BlackAndWhite-aGw9kjsTnAgf0XbbE7Kp9A==/base.apk" mCookie:3865172448
06-27 05:56:40.652 15232 18875 E zjdroid-shell-com.imlk.BlackAndWhite: End DexFile Infomation

**Comment by imlk0** [comment]
#### 问题1：
正常现象，
backsmali命令在art上还不可用，因为Java层用到的库已经太旧太旧了，不支持art，并且新版的接口已经变化太多了，要更新到最新版的话，需要重写很多地方，最近比较忙暂时还没有去搞，
其实大多数情况下就用dump_dexfile命令就足够了，拿出来以后用backsmali 和smali转成dex

#### 问题2：
正常现象，
**每一条输出分四段：**
1. 06-27 05:56:40.652 15232 18875 E zjdroid-shell-com.imlk.BlackAndWhite: 

2. filepath:/data/app/com.imlk.BlackAndWhite-aGw9kjsTnAgf0XbbE7Kp9A==/base.apk 
//先是文件路径，大概和在哪里加载的dex有关

3. dexElementToString:dex file "/data/app/com.imlk.BlackAndWhite-aGw9kjsTnAgf0XbbE7Kp9A==/base.apk" 
//然后是一个dexElement对象的toString()输出结果，增加这个主要是能看出这是个apk还是个dex文件（输出一开头就显示了"dex file"，如果你去dump那个输出是“zip file”的，你会发现拿出来的是壳子）

4. mCookie:3865175168
//这个是重点，dumpdex文件等操作都以这串数字作为标识
