### ISSUE TITLE
64bit so库的问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [KB5201314/ZjDroid#3]
描述一下我的执行命令，

adcast -a com.zjdroid.invoke --ei target 2577 --es cmd '{action:dump_dexfile, mCookie:3865174528}'

然后日志报错如下：

 FATAL EXCEPTION: Thread-4
05-10 15:23:11.789  2577  3628 E AndroidRuntime: Process: com.imlk.BlackAndWhite, PID: 2577
05-10 15:23:11.789  2577  3628 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.imlk.BlackAndWhite/xm_code_cache/xm_secondary-sos/libdvmnative.so" is 64-bit instead of 32-bit
05-10 15:23:11.789  2577  3628 E AndroidRuntime:        at java.lang.Runtime.load0(Runtime.java:928)
05-10 15:23:11.789  2577  3628 E AndroidRuntime:        at java.lang.System.load(System.java:1621)
05-10 15:23:11.789  2577  3628 E AndroidRuntime:        at com.android.reverse.util.SoFileLoader.loadLibrary(SoFileLoader.java:73)
05-10 15:23:11.789  2577  3628 E AndroidRuntime:        at com.android.reverse.util.NativeFunction.<clinit>(NativeFunction.java:20)
05-10 15:23:11.789  2577  3628 E AndroidRuntime:        at com.android.reverse.util.NativeFunction.dumpDexFileByCookie(Native Method)
05-10 15:23:11.789  2577  3628 E AndroidRuntime:        at com.android.reverse.collecter.DexFileInfoCollecter.dumpDexFile(DexFileInfoCollecter.java:264)
05-10 15:23:11.789  2577  3628 E AndroidRuntime:        at com.android.reverse.request.DumpDexFileCommandHandler.doAction(DumpDexFileCommandHandler.java:19)
05-10 15:23:11.789  2577  3628 E AndroidRuntime:        at com.android.reverse.mod.CommandBroadcastReceiver$1.run(CommandBroadcastReceiver.java:31)
05-10 15:23:11.789  2577  3628 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)

是不是so库编译的问题？

用Native Lib Monitor排查了下，初步断定是so库加载了64位版本，我fork下项目，尝试编译的时候只包含32库试试，如果能通过，我自行关闭这个issue

**Comment by imlk0** [comment]
不是编译问题，是加载so的问题，在高版本Android上面，xposed框架默认不会加载so文件，所以我自己加了一个辅助类用于加载so文件
com.android.reverse.util.SoFileLoader.loadLibrary()
其中通过判断build.prop里面当前系统支持的abi类型来解压出so文件，估计是这个判断的逻辑有点问题，如果你感兴趣可以帮忙看看，我得晚上回去才能改

**Comment by imlk0** [comment]
另外，能贴出您的build.prop里和abi有关的四条数据吗
例如：
ro.product.cpu.abi=arm64-v8a
ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=arm64-v8a

**Comment by imlk0** [comment]
嘿，我把它修好了，来试试吧
https://github.com/KB5201314/ZjDroid/releases

**Comment by JamesLiAndroid** [comment]
成功了，已经提取完毕

最后一个事情就是，你的as是怎么配置的NDK，ide版本和NDK版本多少？

我这边as升级到最新以后导入项目无法编译！

**Comment by imlk0** [comment]
as版本为当前最新版
ndk为14

你是ndk部分无法编译对吗
在jni/dvmnative文件夹下有一个Android.mk文件
里面有两个编译模块LOCAL_MODULE
你会发现第一个LOCAL_MODULE里SRC我用的是绝对路径
因为如果用相对路径的话，as似乎有bug，从错误信息看出，它会去找.c文件，而项目里的是.cpp文件，我不知道这是什么原因，而在as外面直接用ndk-build是没有问题的，

所以我把它换成了绝对路径，这才编译成功，你试试换成你电脑上的的绝对路径

**Comment by minliacom** [comment]
用这个方式可以编译
ndk安装的14
LOCAL_SRC_FILES := ./elfinfo.cpp

**Comment by imlk0** [comment]
谢谢:grinning:
