### ISSUE TITLE
6.0上方法原型貌似是这样的

### ISSUE THREAD

**Issue by sgact** [KB5201314/ZjDroid#4]
`            
defineClassNativeMethod = RefInvoke.findMethodExact("dalvik.system.DexFile", ClassLoader.getSystemClassLoader(), "defineClassNative",String.class, ClassLoader.class, Object.class);
`

**Comment by sgact** [comment]
哎呀，原来不支持art啊

**Comment by imlk0** [comment]
@sgact 诶诶诶，支持art的呀

**Comment by sgact** [comment]
额，没看全，是支持的哈，打，打扰了(`・ω・´)

**Comment by imlk0** [comment]
@sgact 欢迎一起来改进哦
